### PR TITLE
tests: try to build Skopeo and pull an image

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
Added a test for building Skopeo and pulling an image to the OSTree storage.

/cc @lucab @ashcrow @cgwalters

**Comment by giuseppe** [comment]
I've changed it to use the latest release tag

**Comment by ashcrow** [comment]
Hrm. Looks like there [is a build issue](https://travis-ci.org/ostreedev/ostree-go/builds/421098348#L1482-L1490).

**Comment by lucab** [comment]
On top of what @ashcrow said, this test means that ostree-go (master) is not allowed to change its public API at all anymore.

I think this is not what we should have here. Some alternatives could be:
 1. split the E2E via skopeo into a separated travis run, which is allowed to run
 1. split the E2E via skopeo to a different CI (cirrus, circle or semaphore), and don't gate PRs on that
 1. move E2E to skopeo land and just wire PR trigger and status report here, and don't gate PRs on that

In the past we setup the latter between rkt (consuming systemd-nspawn) and systemd PRs via rkt-jenkins, and both sides were pretty happy with the result (while it lasted).

**Comment by giuseppe** [comment]
it seems the rename to containers/skopeo breaks the build for the last release tag.  I've added an EPOCH commit to use in case tags are older than that.

@lucab hm.. why should the public API change?  That is one of the things I wanted to test with this PR

**Comment by giuseppe** [comment]
tests are green again

**Comment by lucab** [comment]
@giuseppe it may at any point (on master), depending on development and bugfixing needs (e.g. some of the methods may get a `context` at some point in the future, or be moved around). Go libraries do not guarantee any stability on master, which is the reason why they are commit-pinned and vendored.

**Comment by giuseppe** [comment]
I've splitted the tests, and set `allow_failures` for Skopeo.  Waiting for the CI to complete

**Comment by giuseppe** [comment]
..CI completed and tests are passing

**Comment by giuseppe** [comment]
since the Skopeo tests , can we move it back to test master?  So that if something changes in ostree-go, we can fix it in Skopeo and not wait for a release.

**Comment by lucab** [comment]
@giuseppe you missed a verb, but I think you meant that as the tests are advisory (i.e. non-gating) they can more aggressively track master branches of both repos. That's fine with me.

Can you please also move the script into some dedicated path, like `scripts/travis/test_skopeo.sh`?

Moreover, as you are consuming this in a binary and distributions would need to package this library too, should we start tagging releases once in a while (like we do for [go-systemd](https://github.com/coreos/go-systemd/releases))?

**Comment by lucab** [comment]
Ack. LGTM.

BTW skopeo re-vendoring output has this line:
> WARNING: package github.com/golang/glog is unused, consider removing it from vendor.conf

**Pull request merged**
