### PR TITLE
These casts are needed to get skopeo to compile

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by rhatdan** [comment]
With these patches skopeo in an rpm actually builds.

**Comment by rhatdan** [comment]
@cgwalters could you review and merge this.  We need this so skopeo will compile on Fedora.

**Comment by cgwalters** [comment]
golang became stricter about casts or something?  OK.

**Comment by runcom** [comment]
vendored this in skopeo in PR https://github.com/projectatomic/skopeo/issues/367

**Comment by rhatdan** [comment]
Yes I believe so,  skopeo is compiling on Ubuntu but not on Fedora, I believe this has something to do with the latest golang compiler.

**Comment by rhatdan** [comment]
@runcom we need a version bump to 1.22 for build in fedora.

**Comment by runcom** [comment]
@rhatdan I'll wait for https://github.com/projectatomic/skopeo/pull/366 before doing a new release

**Comment by rhatdan** [comment]
Makes sense.  Thanks.

**Pull request merged**
