### PR TITLE
Refactor Commit

### PR DESCRIPTION
**Pull request by giuseppe**
I ported here the changes proposed in: https://github.com/ostreedev/ostree/pull/689

### CODE REVIEW

**Comment by giuseppe** [comment]
I changed this series to something different, since the changes in ostree.go won't even build with this version.  It seems ostree/ is not maintained/used.  Should it be deleted?

**Comment by giuseppe** [comment]
I added a few more commits

**Comment by 14rcole** [comment]
I wasn't sure if I should delete ostree.  That code is a copy of the code from contrib/golang in the ostree repository.  I thought I should leave it in there in case anybody used that code for some reason.  That being said, I don't see any particular use for it and would be comfortable deleting it.

I do have one question about your PR.  It seems like all of the functions that you added are public.  Do you see a use for these functions in other projects/packages?  Otherwise I would imagine it makes more sense to keep them private and only expose the Commit() function.

**Comment by giuseppe** [comment]
I think it is the caller responsibility to start/commit the transaction so we follow better the libostree APIs.  I would like to use them to have different commits in one single transaction

**Comment by giuseppe** [comment]
I pushed another patch to rm -rf ostree.  If we will ever need it, then we can find it in the git history

**Comment by 14rcole** [comment]
LGTM.  I'll merge it

**Comment by 14rcole** [comment]
Looks good to me, merged the changes

**Comment by giuseppe** [comment]
ouch, why was it merged as squashed?  The commit looks much worse now

**Comment by 14rcole** [comment]
I thought that commits were supposed to be squashed before being merged into master?

**Comment by giuseppe** [comment]
no they were separated commits

**Pull request merged**
